// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for ClockDriftFunction
 */
export interface ClockDriftFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/ClockDriftLambda/ClockDrift.
 */
export class ClockDriftFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ClockDriftFunctionProps) {
    super(scope, id, {
      description: 'src/ClockDriftLambda/ClockDrift.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/ClockDriftLambda/ClockDrift.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}