// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for LogQueryJobFunction
 */
export interface LogQueryJobFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/LogQueryJob/LogQueryJob.
 */
export class LogQueryJobFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: LogQueryJobFunctionProps) {
    super(scope, id, {
      description: 'src/LogQueryJob/LogQueryJob.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/LogQueryJob/LogQueryJob.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}