// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for EnableSsmDocShareProtectionFunction
 */
export interface EnableSsmDocShareProtectionFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/CustomResources/SsmDocumentSharing/enableSsmDocShareProtection.
 */
export class EnableSsmDocShareProtectionFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: EnableSsmDocShareProtectionFunctionProps) {
    super(scope, id, {
      description: 'src/CustomResources/SsmDocumentSharing/enableSsmDocShareProtection.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/CustomResources/SsmDocumentSharing/enableSsmDocShareProtection.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}