// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for HealthEventFunction
 */
export interface HealthEventFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/healthGrouping/healthEventLambda/healthEvent.
 */
export class HealthEventFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: HealthEventFunctionProps) {
    super(scope, id, {
      description: 'src/healthGrouping/healthEventLambda/healthEvent.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/healthGrouping/healthEventLambda/healthEvent.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}